defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: famlog_dev

test:
  <<: *defaults
  database: famlog_test

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
  #host: db.mongohq.com
  username: user
  password: pass
  database: famlog

