development:
  mail: &mail
    admin_email: admin_email
    host: host
    address: address
    port: port
    domain: domain
    user_name: user_name
    password: password
    authentication: authentication
    enable_starttls_auto: enable_starttls_auto

test:
  mail:
    <<: *mail

production:
  mail:
    <<: *mail

